"""
Alternative credit scorecard for informal/gig workers — training pipeline.

Trains on ml/derived_training_data.csv, which is generated by
scripts/generate-training-data.ts using the SAME transaction-generator ->
Cashflow Intelligence Engine pipeline the live app runs — so the model is
fit on the actual feature distribution it sees in production, not a
separately hand-authored one. Trains a Logistic Regression scorecard model
(deployed) plus a Random Forest benchmark (reported for rigor only), and
exports the trained scorecard as a JSON artifact consumed directly by the
Next.js app (no Python runtime needed in production).

Run:
  npx tsx scripts/generate-training-data.ts   (regenerate the CSV, optional)
  python ml/train_model.py
"""

import json
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler

# ---------------------------------------------------------------------------
# 1. Load the derived training set
# ---------------------------------------------------------------------------

data_path = Path(__file__).parent / "derived_training_data.csv"
df = pd.read_csv(data_path)

FEATURE_ORDER = [c for c in df.columns if c != "is_good"]
N = len(df)
is_good = df["is_good"]

FEATURE_META = {
    "avg_monthly_income": {"label": "Average monthly income", "higherIsBetter": True, "unit": "INR"},
    "income_consistency": {"label": "Income consistency", "higherIsBetter": True, "unit": "ratio"},
    "avg_monthly_txn_count": {"label": "Monthly digital transactions", "higherIsBetter": True, "unit": "count"},
    "txn_consistency": {"label": "Transaction consistency", "higherIsBetter": True, "unit": "ratio"},
    "utility_ontime_rate": {"label": "Utility bill on-time rate", "higherIsBetter": True, "unit": "ratio"},
    "platform_tenure_months": {"label": "Work/platform tenure", "higherIsBetter": True, "unit": "months"},
    "customer_rating": {"label": "Customer rating", "higherIsBetter": True, "unit": "stars"},
    "cancellation_rate": {"label": "Cancellation rate", "higherIsBetter": False, "unit": "ratio"},
    "savings_rate": {"label": "Savings rate", "higherIsBetter": True, "unit": "ratio"},
    "debt_to_income": {"label": "Existing debt-to-income", "higherIsBetter": False, "unit": "ratio"},
}

print(f"Derived training set: {N} rows, default rate = {(1 - is_good.mean()):.1%}")

# ---------------------------------------------------------------------------
# 2. Train/test split + standardization
# ---------------------------------------------------------------------------

X = df[FEATURE_ORDER].values
y = df["is_good"].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler().fit(X_train)
X_train_s = scaler.transform(X_train)
X_test_s = scaler.transform(X_test)

# ---------------------------------------------------------------------------
# 3. Deployed model: Logistic Regression scorecard
# ---------------------------------------------------------------------------

logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train_s, y_train)

logreg_proba = logreg.predict_proba(X_test_s)[:, 1]
logreg_pred = (logreg_proba >= 0.5).astype(int)
logreg_auc = roc_auc_score(y_test, logreg_proba)
logreg_acc = accuracy_score(y_test, logreg_pred)
logreg_cm = confusion_matrix(y_test, logreg_pred).tolist()

print(f"Logistic Regression  AUC={logreg_auc:.4f}  Accuracy={logreg_acc:.4f}")
print(f"Confusion matrix (rows=actual, cols=pred) [bad, good]: {logreg_cm}")

# ---------------------------------------------------------------------------
# 4. Benchmark model: Random Forest (reported only, not deployed)
# ---------------------------------------------------------------------------

rf = RandomForestClassifier(n_estimators=300, max_depth=8, random_state=42)
rf.fit(X_train_s, y_train)
rf_proba = rf.predict_proba(X_test_s)[:, 1]
rf_auc = roc_auc_score(y_test, rf_proba)
rf_acc = accuracy_score(y_test, (rf_proba >= 0.5).astype(int))

print(f"Random Forest (benchmark)  AUC={rf_auc:.4f}  Accuracy={rf_acc:.4f}")

# ---------------------------------------------------------------------------
# 5. Points-scaling: map log-odds of "good" to a 300-900 scorecard range
# ---------------------------------------------------------------------------

log_odds_train = logreg.decision_function(X_train_s)
log_odds_min = float(np.percentile(log_odds_train, 0.5))
log_odds_max = float(np.percentile(log_odds_train, 99.5))

SCORE_MIN, SCORE_MAX = 300, 900

# ---------------------------------------------------------------------------
# 6. Export scorecard artifact for the Next.js app
# ---------------------------------------------------------------------------

artifact = {
    "version": 1,
    "trainedAt": pd.Timestamp.now("UTC").isoformat(),
    "scoreRange": {"min": SCORE_MIN, "max": SCORE_MAX},
    "logOddsRange": {"min": log_odds_min, "max": log_odds_max},
    "intercept": float(logreg.intercept_[0]),
    "features": [
        {
            "name": name,
            "label": FEATURE_META[name]["label"],
            "unit": FEATURE_META[name]["unit"],
            "higherIsBetter": FEATURE_META[name]["higherIsBetter"],
            "coefficient": float(logreg.coef_[0][i]),
            "mean": float(scaler.mean_[i]),
            "scale": float(scaler.scale_[i]),
            "trainMin": float(X_train[:, i].min()),
            "trainMax": float(X_train[:, i].max()),
        }
        for i, name in enumerate(FEATURE_ORDER)
    ],
    "metrics": {
        "datasetSize": N,
        "defaultRate": float(1 - is_good.mean()),
        "logisticRegression": {"auc": float(logreg_auc), "accuracy": float(logreg_acc), "confusionMatrix": logreg_cm},
        "randomForestBenchmark": {"auc": float(rf_auc), "accuracy": float(rf_acc)},
    },
}

out_path = Path(__file__).parent.parent / "src" / "lib" / "scoring" / "model-coefficients.json"
out_path.parent.mkdir(parents=True, exist_ok=True)
out_path.write_text(json.dumps(artifact, indent=2))
print(f"\nWrote scorecard artifact to {out_path}")

# Also drop a copy of the training sample for the notebook/pitch deck
sample_path = Path(__file__).parent / "synthetic_sample.csv"
df.sample(500, random_state=1).to_csv(sample_path, index=False)
print(f"Wrote 500-row sample dataset to {sample_path}")
